In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
arr1 = np.array([1,2,3]) 
arr1

array([1, 2, 3])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]],dtype='complex')
arr2

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [5]:
type(arr2[0][0])

numpy.complex128

In [6]:
a = np.linspace(0.00,0.04,100001)
a

array([0.00000e+00, 4.00000e-07, 8.00000e-07, ..., 3.99992e-02,
       3.99996e-02, 4.00000e-02])

In [7]:
z = np.zeros((6,6),dtype=np.int)
z

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [8]:
z.reshape(2,18)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
o = np.ones((2,5,4),dtype=np.int)
o

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [10]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
data = np.array(['a','b','c','d'])
data

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [12]:
pd.Series(data,index=np.arange(1,5))

1    a
2    b
3    c
4    d
dtype: object

In [13]:
df = pd.read_csv('iris.csv')

In [14]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [15]:
df.shape

(150, 5)

In [16]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [18]:
df.target_name()

AttributeError: 'DataFrame' object has no attribute 'target_name'